# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- dev_demo

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: npm install
  displayName: 'npm install'

- script: docker build -t mainapp:$(Build.BuildId) .
  displayName: 'Build an image'

- script: |
    docker tag mainapp:$(Build.BuildId) demonodejs.azurecr.io/mainapp:$(Build.BuildId)
    docker login demonodejs.azurecr.io -u df7c2cb1-592c-43a4-8e45-564193544739 -p cffae9ee-aceb-43e1-bd80-5d13a3b720ef
    docker push demonodejs.azurecr.io/mainapp:$(Build.BuildId)
  displayName: 'Tag, login and push mainapp image to Azure Container Registry'